version: '3'

services:

  proxy:
    build: ./nginx
    container_name: proxy
    networks:
      - proxy
    ports:
      - "80:80"
    restart: always

  nodees6:
    build: .
    container_name: nodees6
    environment:
      - NODE_ENV=production
      - HOST=nodees6
    networks:
      - proxy
    restart: always

networks:
  proxy:
    driver: bridge
