version: '3'

services:

  nodees6:
    build: .
    image: yuttasakcom/nodees6:1.0.0
    container_name: nodees6
    environment:
      - HOST=nodees6
    # ports:
    #   - "3000:3000"
    networks:
      - proxy
    restart: always

networks:
  proxy:
    external: true
